// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Expense struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	FinancialYear  int32
	IssueDate      time.Time
	Company        string
	PaymentOption  string
	Account        string
	Amount         float64
	IsVat          bool
	Total          float64
}

type FinancialAccount struct {
	ID             uuid.UUID
	OrganizationID uuid.UUID
	Name           string
	Key            string
	IsVat          bool
}

type FinancialYear struct {
	OrganizationID uuid.UUID
	Year           int32
}

type Invoice struct {
	OrganizationID  uuid.UUID
	Number          int32
	FinancialYear   int32
	IssueDate       sql.NullTime
	Name            sql.NullString
	Email           sql.NullString
	Phone           sql.NullString
	CarRegistration sql.NullString
	Total           float64
	IsVat           bool
}

type InvoiceProduct struct {
	ID             int32
	InvoiceNumber  int32
	OrganizationID uuid.UUID
	Serial         sql.NullString
	Description    string
	Quantity       int32
	Rate           float64
	Total          float64
}

type Organization struct {
	ID                 uuid.UUID
	InvoiceNumberStart string
}

type UsersOrganization struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}
