// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Company struct {
	ID        uuid.UUID
	Name      string
	Cvr       sql.NullInt32
	CreatedAt interface{}
	UpdatedAt interface{}
}

type Cost struct {
	ID            uuid.UUID
	InvoiceID     uuid.UUID
	ProductNumber sql.NullString
	Description   sql.NullString
	Quantity      float64
	UnitPrice     float64
	Total         float64
}

type Customer struct {
	ID              uuid.UUID
	CarRegistration sql.NullString
	InvoiceID       uuid.UUID
	Name            sql.NullString
	Email           sql.NullString
	Phone           sql.NullString
	Address         sql.NullString
	ZipCode         sql.NullString
	CreatedAt       sql.NullTime
}

type Expense struct {
	ID           uuid.UUID
	TotalExclVat float64
	TotalInclVat float64
	VatAmount    float64
	VatRate      float64
	IssuedAt     time.Time
	PaidAt       sql.NullTime
	PaidWith     sql.NullInt32
	CompanyID    uuid.UUID
}

type ExpensesEntry struct {
	ID           uuid.UUID
	ExpenseID    uuid.UUID
	Serial       sql.NullString
	Description  sql.NullString
	UnitPrice    float64
	Quantity     int32
	TotalExclVat float64
	TotalInclVat float64
}

type Invoice struct {
	ID              uuid.UUID
	InvoiceNumber   int32
	IssuedAt        sql.NullTime
	VatPercentage   float64
	VatAmount       float64
	TotalExcludeVat float64
	TotalIncludeVat float64
	PaymentStatus   interface{}
}

type InvoiceMigration struct {
	ID                      uuid.UUID
	InvoiceNumber           int32
	FailedAt                sql.NullTime
	FilePath                sql.NullString
	HasMigratedSuccessfully sql.NullInt32
	LastFailedAttempt       sql.NullTime
}

type Payment struct {
	ID        uuid.UUID
	InvoiceID uuid.UUID
	Amount    float64
	PaidAt    sql.NullTime
	Method    string
}
