// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO organizations (
	id,
	name
) VALUES (
	$1,
	$2
)
`

type CreateOrganizationParams struct {
	ID   uuid.UUID
	Name string
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.ExecContext(ctx, createOrganization, arg.ID, arg.Name)
	return err
}

const createOrganizationUser = `-- name: CreateOrganizationUser :exec
INSERT INTO users_organizations (
	organization_id,
	user_id
) VALUES (
	$1,
	$2
)
`

type CreateOrganizationUserParams struct {
	OrganizationID uuid.UUID
	UserID         uuid.UUID
}

func (q *Queries) CreateOrganizationUser(ctx context.Context, arg CreateOrganizationUserParams) error {
	_, err := q.db.ExecContext(ctx, createOrganizationUser, arg.OrganizationID, arg.UserID)
	return err
}

const getAllInvoicesByOrganizationId = `-- name: GetAllInvoicesByOrganizationId :many
SELECT organization_id, number, financial_year, issue_date, name, email, phone, car_registration, total, is_vat FROM invoices WHERE organization_id = $1
`

func (q *Queries) GetAllInvoicesByOrganizationId(ctx context.Context, organizationID uuid.UUID) ([]Invoice, error) {
	rows, err := q.db.QueryContext(ctx, getAllInvoicesByOrganizationId, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invoice
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.OrganizationID,
			&i.Number,
			&i.FinancialYear,
			&i.IssueDate,
			&i.Name,
			&i.Email,
			&i.Phone,
			&i.CarRegistration,
			&i.Total,
			&i.IsVat,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProductsByInvoiceId = `-- name: GetAllProductsByInvoiceId :many
SELECT id, invoice_number, organization_id, serial, description, quantity, rate, total FROM invoice_products WHERE organization_id = $1 AND invoice_number = $2
`

type GetAllProductsByInvoiceIdParams struct {
	OrganizationID uuid.UUID
	InvoiceNumber  int32
}

func (q *Queries) GetAllProductsByInvoiceId(ctx context.Context, arg GetAllProductsByInvoiceIdParams) ([]InvoiceProduct, error) {
	rows, err := q.db.QueryContext(ctx, getAllProductsByInvoiceId, arg.OrganizationID, arg.InvoiceNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InvoiceProduct
	for rows.Next() {
		var i InvoiceProduct
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.OrganizationID,
			&i.Serial,
			&i.Description,
			&i.Quantity,
			&i.Rate,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationByUserId = `-- name: GetOrganizationByUserId :one
SELECT organization_id, user_id FROM users_organizations WHERE user_id =$1
`

func (q *Queries) GetOrganizationByUserId(ctx context.Context, userID uuid.UUID) (UsersOrganization, error) {
	row := q.db.QueryRowContext(ctx, getOrganizationByUserId, userID)
	var i UsersOrganization
	err := row.Scan(&i.OrganizationID, &i.UserID)
	return i, err
}
